### ISSUE TITLE
Adding AA Greenhouse Glass from JEI to refined storage crafting grid causes disconnect

### ISSUE THREAD

**Issue by lhw** [AllTheMods/ATM3-Remix#210]
Adding the greenhouse glass recipe from the JEI interface to the crafting grid causes a disconnect.

## Expected Behavior

It adds the recipe

## Current Behavior

it doesn't disconnect me

## Possible Solution

Modify the recipe size to a few tree saplings/glass variants

## Steps to Reproduce

1. JEI on greenhouse glass
2. Click +
3. See error message 
4. Reconnect to have fun again

## Log
```
22:30:37] [Client thread/WARN] [jei]: Recipe registry plugin is slow, took 18.77 ms. class crazypants.enderio.base.integration.jei.DarkSteelUpgradeRecipeCategory$1
[22:30:37] [Client thread/WARN] [jei]: Recipe registry plugin is slow, took 38.73 ms. class crazypants.enderio.base.integration.jei.DarkSteelUpgradeRecipeCategory$1
[22:30:39] [Netty Epoll Client IO #2/ERROR] [FML]: NetworkDispatcher exception
java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes
	at net.minecraft.network.play.client.CPacketCustomPayload.<init>(CPacketCustomPayload.java:28) ~[lh.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.toC17Packet(FMLProxyPacket.java:142) ~[FMLProxyPacket.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:533) ~[NetworkDispatcher.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:245) [gw$4.class:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

## Detailed Description

Adding the greenhouse glass recipe from the JEI interface to the crafting grid causes an issue with the packet size of the recipe. As can be seen in the stacktrace below. I do not know if this is because of changes to the recipe in ATM3 or just a bug with the two mod interactions. I might try to find that out later.

**Comment by Yamza** [comment]
Known issue with Refined Storage. Insert the items manually. https://github.com/AllTheMods/ATM3-Remix/issues/82

**Comment by lhw** [comment]
Yeah looks like it. But hasn't been fixed yet. https://github.com/raoulvdberge/refinedstorage/issues/1790

**Comment by lhw** [comment]
I mean you can close it but the bug exists in the pack and is not fixed...

**Comment by Darkere** [comment]
We cannot fix this bug. It's on the moddev to fix it. This is also a duplicate.
