### ISSUE TITLE
 [File IO Thread/ERROR] [minecraft/AnvilChunkLoader]: Failed to save chunk

### ISSUE THREAD

**Issue by OfficialStamper** [AllTheMods/ATM3-Remix#24]
Getting the following error in Mining Dimension with Chunks Loaded and no player present in the Dimension:
```
[12:22:41] [File IO Thread/ERROR] [minecraft/AnvilChunkLoader]: Failed to save chunk
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:1.8.0_181]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1466) ~[?:1.8.0_181]
        at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:32) ~[fy.class:?]
        at net.minecraft.nbt.CompressedStreamTools.func_150663_a(CompressedStreamTools.java:112) ~[gi.class:?]
        at net.minecraft.nbt.CompressedStreamTools.func_74800_a(CompressedStreamTools.java:102) ~[gi.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_183013_b(AnvilChunkLoader.java:241) ~[aye.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75814_c(AnvilChunkLoader.java:219) [aye.class:?]
        at net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(SourceFile:37) [bgx.class:?]
        at net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:30) [bgx.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```
The only thing running in the Dim are CC Turtles, doing some mining, they continue to work as normal, but the error worries me, even though nothing seems to get lost

EDIT:

ATM3 Remix (Dev Branch)
```
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.4.0-134-generic
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3459018584 bytes (3298 MB) / 7328301056 bytes (6988 MB) up to 7328301056 bytes (6988 MB)
	JVM Flags: 15 total; -Xmx7G -Xms7G -XX:+AggressiveOpts -XX:ParallelGCThreads=3 -XX:+UseConcMarkSweepGC -XX:+UnlockExperimentalVMOptions -XX:+UseParNewGC -XX:+ExplicitGCInvokesConcurrent -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:NewSize=84m -XX:+UseAdaptiveGCBoundary -XX:NewRatio=3
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.4.2756 282 mods loaded, 282 mods active
```

**Comment by KaneHart** [comment]
You left out way too much info. Like is this client or server? If server is it vanilla forge or not. If Sponge you using any plugins cause asyncing save, etc.

Need a lot more details. 

Also when you shutdown the game those chunks might actually not save right.

**Comment by OfficialStamper** [comment]
See edits above for versions etc.
There are no permission issues.  
If a player enters the Dimension, the errors stop spamming the console.

I would expect the error can be re-created on any server with the following steps:
1) Travel to mining dimension -6
2) Claim and Load Chunk(s) via FTBU
3) Put a CC Mining Turtle to mine some blocks in the loaded chunks.
4) Leave dimension
5) Errors should appear in console every few minutes (assuming turtle is still operating)

Hope this helps, let me know if I can help further

**Comment by Yamza** [comment]
You might want to test and confirm this with just the mods required to make it happen. Aromas, FTBU and the Turtles. If you can confirm with such a configuration it would be best to send reports to those mod authors.

**Comment by OfficialStamper** [comment]
Unfortunately, I do not have an environment to test with just the 3 mods in question. It would mean shutting my server down to perform those test and thats not an option currently. Sorry.

If you are unable to recreate in your dev environments, and thus, do not believe there is an issue with the ATM3 Remix pack, then just close the issue and lets hope others dont experience the same problem when it finally goes live.  I was just trying to help by reporting a possible problem before live.

Thanks, keep up the good work
