### ISSUE TITLE
Server installer unstable and crashing

### ISSUE THREAD

**Issue by RedTech64** [AllTheMods/ATM3-Remix#354]
## Expected Behavior
Server will install and run without crashing.

## Current Behavior
Just by starting the server eventually, the following error is displayed and the server crashes.

```
[21:45:28] [ERROR] Some uncaught error happened.

kotlin.TypeCastException: null cannot be cast to non-null type kotlin.String
        at atm.bloodworkxgaming.serverstarter.ForgeManager.startServer(ForgeManager.kt:163)
        at atm.bloodworkxgaming.serverstarter.ForgeManager.handleServer(ForgeManager.kt:42)
        at atm.bloodworkxgaming.serverstarter.ServerStarter.startLoading(ServerStarter.kt:184)
        at atm.bloodworkxgaming.serverstarter.ServerStarterKt.main(ServerStarter.kt:195)
```

This happened after the startup got stuck and I had to kill the server. It also started once on the first startup. I have tried deleting everything and starting over 4 times and could not avoid this crash. Seems like server starter has some significant problems. I did try to delete the .lock file but that did not solve the problem.

I understand there is a way to just run it traditionally without serverstarter but I do not have the patience for that at this point.

## Possible Solution
Stop using serverstarter or fix it so it is not so unreliable.

## Steps to Reproduce
1. Start server
2. Simulate the server getting stuck on startup (after serverstarter installs everything)
3. Kill the server
4. Try starting it again

I did even get it right after typing in TRUE for the eula. There seems to be multiple places this can cause a crash.

## Log
```
INFO: Checking java installation...

java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)

INFO: Found 64-bit Java 1.8
[21:49:55] [INFO] ::::::::::::::::::::::::::::::::::::::::::::::::::::
[21:49:55] [INFO]    Minecraft-Forge Server install/launcher jar
[21:49:55] [INFO]    (Created by the "All The Mods" modpack team)
[21:49:55] [INFO] ::::::::::::::::::::::::::::::::::::::::::::::::::::
[21:49:55] [INFO]
[21:49:55] [INFO]    This jar will launch a Minecraft Forge Modded server
[21:49:55] [INFO]
[21:49:55] [INFO]    Github:    https://github.com/AllTheMods/ServerStarter
[21:49:55] [INFO]    Discord:   http://discord.allthepacks.com
[21:49:55] [INFO]
[21:49:55] [INFO] You are playing All the Mods 3 Remix
[21:49:55] [INFO] Starting to install/launch the server, lean back!
[21:49:55] [INFO] ::::::::::::::::::::::::::::::::::::::::::::::::::::
[21:49:55] [INFO]
[21:49:55] [INFO] Pinging 8.8.8.8.
[21:49:55] [INFO] Reached 8.8.8.8: true
[21:49:55] [INFO] Pinging 1.1.1.1.
[21:49:55] [INFO] Reached 1.1.1.1: true
[21:49:55] [INFO] Reached 2 out of 2 IPs.
[21:49:55] [INFO] Server is already installed to correct version, to force install delete the serverstarter.lock File.
[21:49:55] [ERROR] Some uncaught error happened.

kotlin.TypeCastException: null cannot be cast to non-null type kotlin.String
        at atm.bloodworkxgaming.serverstarter.ForgeManager.startServer(ForgeManager.kt:163)
        at atm.bloodworkxgaming.serverstarter.ForgeManager.handleServer(ForgeManager.kt:42)
        at atm.bloodworkxgaming.serverstarter.ServerStarter.startLoading(ServerStarter.kt:184)
        at atm.bloodworkxgaming.serverstarter.ServerStarterKt.main(ServerStarter.kt:195)
```

**Comment by Bigdeath** [comment]
Same Problem. When deleting server.properties then it try to run. 

` [ERROR] Some uncaught error happened.

kotlin.TypeCastException: null cannot be cast to non-null type kotlin.String
        at atm.bloodworkxgaming.serverstarter.ForgeManager.startServer(ForgeManager.kt:163)
        at atm.bloodworkxgaming.serverstarter.ForgeManager.handleServer(ForgeManager.kt:42)
        at atm.bloodworkxgaming.serverstarter.ServerStarter.startLoading(ServerStarter.kt:184)
        at atm.bloodworkxgaming.serverstarter.ServerStarterKt.main(ServerStarter.kt:195)
startserver.sh: 13: startserver.sh: [[: not found
`

**Comment by compwiz91** [comment]
Anyone found a solution or work around to this issue? Or information as to why it occurs.

**Comment by connorb777** [comment]
I have the same issue, redownloading the server files did nothing. Might try an older version.

**Comment by Quarkonone** [comment]
Hello, is this a linux server? And did you used the command "sudo bash startserver.sh"?
